name: ASP.NET Core CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['2.2.207', '2.2.108', '2.2.110', '2.2.402']
        os: [ubuntu-latest, windows-latest, macOS-latest]

        
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet_version }}
    
    - name: Restore
      run: dotnet restore
      working-directory: ./DemoApp
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./DemoApp


    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o netcore 
      working-directory: ./DemoApp
      
