name: ASP.NET Core CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    
    - name: Restore
      run: dotnet restore
      working-directory: ./DemoApp
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./DemoApp


    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o netcore 
      working-directory: ./DemoApp
  
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: DemoApp/DemoApp/netcore/
    
    - name: Zip Artifact
      run: zip DemoApp/DemoApp/netcore  
  
