# This is a basic workflow to help you get started with Actions

name: TesteAction

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: docker pull node:latest
    - run: docker tag node:latest myregistry.azurecr.io/hello-world:v2
    - name: Push Image to ACR
      uses: julioarruda/pushimagetoacr@v0
      with:
        acr-tokenname: ${{ secrets.ACR_TOKEN_NAME }}
        acr-token: ${{ secrets.ACR_TOKEN_VALUE }}
        acr-account: myregistry.azurecr.io
        imagename: myregistry.azurecr.io/hello-world:v2
